<<<<<<< HEAD
# Nombre de la aplicación
spring.application.name=MarFuego

# ===============================
# CONFIGURACIÓN MYSQL
# ===============================

=======
spring.application.name=ms-menu
server.port=8080

# CONFIGURACIÓN MYSQL
>>>>>>> master
spring.datasource.url=jdbc:mysql://localhost:3306/marfuegodb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

<<<<<<< HEAD
# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# PUERTO DEL SERVIDOR
# ===============================

server.port=8080
=======
# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Mantiene los datos y solo actualiza si hay cambios en las clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> master
