# Nombre de la aplicación
spring.application.name=MarFuego

# ===============================
# CONFIGURACIÓN MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/marfuegodb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# PUERTO DEL SERVIDOR
# ===============================

server.port=8080