spring.application.name=ms-menu
server.port=8082

# CONFIGURACION MYSQL (BD propia para ms-menu)
spring.datasource.url=jdbc:mysql://localhost:3306/marfuego_menu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LOGGING
logging.level.com.Gastronomia.MarFuego=DEBUG
