spring.application.name=ms-reportes
server.port=8086

# Este microservicio NO tiene base de datos.
# Solo consume datos de los otros microservicios via WebClient.

# URLs de los microservicios a los que llama
ms.locales.url=http://localhost:8081
ms.menu.url=http://localhost:8082
ms.inventario.url=http://localhost:8083
ms.pedidos.url=http://localhost:8084
# ms.caja.url=http://localhost:8085

# LOGGING
logging.level.com.marfuego.ms_reportes=DEBUG
