spring.application.name=MarFuego

# Configuración de Base de Datos H2 para Inforge

spring.datasource.url=jdbc:h2:mem:marfuegodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola H2 (para ver las tablas en el navegador)

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actualización automática de tablas según tus modelos

spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola de IntelliJ
spring.jpa.show-sql=true

# Puerto del microservicio (Postman usará http://localhost:8080)
server.port=8080
