spring.application.name=ms-locales
server.port=8081

# CONFIGURACION MYSQL (BD propia para ms-locales)
spring.datasource.url=jdbc:mysql://localhost:3306/marfuego_locales?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LOGGING
logging.level.com.marfuego.ms_locales=DEBUG
